//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongExplorer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetListSong
    {
        public int SetListId { get; set; }
        public int Position { get; set; }
        public int SongId { get; set; }
    
        public virtual SetList SetList { get; set; }
        public virtual Song Song { get; set; }
    }
}
