//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongExplorer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SongExplorerEntities : DbContext
    {
        public SongExplorerEntities()
            : base("name=SongExplorerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Key> Keys { get; set; }
        public virtual DbSet<SetList> SetLists { get; set; }
        public virtual DbSet<SetListSong> SetListSongs { get; set; }
        public virtual DbSet<Slot> Slots { get; set; }
        public virtual DbSet<Song> Songs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Vocalist> Vocalists { get; set; }
    }
}
