//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongExplorer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.SetListSongs = new HashSet<SetListSong>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> KeyId { get; set; }
        public Nullable<int> SlotId { get; set; }
        public Nullable<int> VocalistId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string UserId { get; set; }
    
        public virtual Key Key { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetListSong> SetListSongs { get; set; }
        public virtual Slot Slot { get; set; }
        public virtual Status Status { get; set; }
        public virtual Vocalist Vocalist { get; set; }
    }
}
